baseURL: "http://heyagain.net"
languageCode: "en-us"
title: "0xMilica Web3 Blog"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 2
    - identifier: "blog"
      name: "Blog"
      url: "/posts/"
      weight: 3
    - identifier: "contact"
      name: "Contact"
      url: "/contact/"
      weight: 4